name: Deploy to AWS

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify AWS Credentials
        run: |
          aws sts get-caller-identity
          aws iam get-user

      - name: Install Serverless
        run: npm install -g serverless

      - name: Deploy to dev
        if: github.ref == 'refs/heads/dev'
        run: |
          echo "Deploying to dev environment..."
          npx serverless deploy --stage dev --region us-east-1 --verbose

      - name: Deploy to prod
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying to prod environment..."
          npx serverless deploy --stage prod --region us-east-1 --verbose
